[custom]
;不要随意改变关键字，否则会导致出错
;acl4SSR规则-在线更新版

;去广告：支持
;自动测速：支持
;微软分流：支持
;苹果分流：支持
;增强中国IP段：不支持
;增强国外GFW：不支持
;多国家分组：支持港/日/美

ruleset=🚀 节点选择,https://raw.githubusercontent.com/cmliu/ACL4SSR/refs/heads/main/Clash/PlayStore.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/cmliu/ACL4SSR/refs/heads/main/Clash/CFnat.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/LocalAreaNetwork.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/AndroidDeals/ACL4SSR/main/Clash/UnBan.list
ruleset=⚓ 22端口,[]DST-PORT,22
ruleset=🛑 全球拦截,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanAD.list
ruleset=🍃 应用净化,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanProgramAD.list
ruleset=🍃 应用净化,https://raw.githubusercontent.com/cmliu/ACL4SSR/main/Clash/adobe.list
ruleset=🍃 应用净化,https://raw.githubusercontent.com/cmliu/ACL4SSR/main/Clash/IDM.list
ruleset=🤖 OpenAi,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/OpenAi.list
ruleset=🤖 OpenAi,https://raw.githubusercontent.com/cmliu/ACL4SSR/refs/heads/main/Clash/ai.list
ruleset=🤖 OpenAi,https://raw.githubusercontent.com/cmliu/ACL4SSR/main/Clash/Copilot.list
ruleset=🤖 OpenAi,https://raw.githubusercontent.com/cmliu/ACL4SSR/main/Clash/GithubCopilot.list
ruleset=🤖 OpenAi,https://raw.githubusercontent.com/cmliu/ACL4SSR/main/Clash/Claude.list
ruleset=☁️ CloudFlareCDN,https://raw.githubusercontent.com/cmliu/ACL4SSR/main/Clash/CloudflareCIDR.list
ruleset=📢 谷歌FCM,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/GoogleFCM.list
ruleset=🚀 节点选择,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/GoogleCN.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/SteamCN.list
ruleset=Ⓜ️ 微软服务,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Microsoft.list
ruleset=🍎 苹果服务,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Apple.list
ruleset=📲 电报信息,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Telegram.list
ruleset=📹 油管视频,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/YouTube.list
ruleset=🎥 奈飞视频,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Netflix.list
ruleset=🌍 国外媒体,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyMedia.list
ruleset=🌍 国外媒体,https://raw.githubusercontent.com/cmliu/ACL4SSR/main/Clash/Emby.list
ruleset=🚀 节点选择,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyLite.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaDomain.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaCompanyIp.list
;ruleset=🎯 全球直连,[]GEOIP,LAN
ruleset=☁️ CloudFlareCDN,[]GEOIP,cloudflare
ruleset=🎯 全球直连,[]GEOIP,CN
ruleset=🐟 漏网之鱼,[]FINAL

custom_proxy_group=🚀 节点选择`select`[]♻️ 自动选择`[]🇭🇰 香港节点`[]🇺🇲 美国节点`[]🇯🇵 日本节点`[]🇸🇬 狮城节点`[]🇹🇼 台湾节点`[]🇰🇷 韩国节点`[]🇩🇪 德国节点`[]🇬🇧 英国节点`[]🇳🇱 荷兰节点`[]🇹🇷 土耳其节点`[]🇦🇺 澳大利亚节点`[]🇷🇺 俄罗斯节点`[]🇮🇳 印度节点`[]🇨🇦 加拿大节点`[]🇲🇾 马来西亚节点`[]🇧🇬 保加利亚节点`[]🇫🇷 法国节点`[]🇻🇳 越南节点`[]🇲🇳 蒙古节点`[]🇲🇴 澳门节点`[]🇸🇪 瑞典节点`[]🇮🇸 冰岛节点`[]🇮🇱 以色列节点`[]🇦🇪 阿联酋节点`[]🇵🇭 菲律宾节点`[]🇮🇪 爱尔兰节点`[]☑️ 手动切换`[]DIRECT
custom_proxy_group=⚓ 22端口`select`[]🇯🇵 日本节点`[]🇸🇬 狮城节点`[]🇹🇼 台湾节点`[]🇰🇷 韩国节点`[]🇩🇪 德国节点`[]🇬🇧 英国节点`[]🇳🇱 荷兰节点`[]🇹🇷 土耳其节点`[]🇦🇺 澳大利亚节点`[]🇷🇺 俄罗斯节点`[]🇮🇳 印度节点`[]🇨🇦 加拿大节点`[]🇲🇾 马来西亚节点`[]🇧🇬 保加利亚节点`[]🇫🇷 法国节点`[]🇻🇳 越南节点`[]🇲🇳 蒙古节点`[]🇲🇴 澳门节点`[]🇸🇪 瑞典节点`[]🇮🇸 冰岛节点`[]🇮🇱 以色列节点`[]🇦🇪 阿联酋节点`[]🇵🇭 菲律宾节点`[]🇮🇪 爱尔兰节点`[]DIRECT`[]🚀 节点选择`[]♻️ 自动选择`[]🇭🇰 香港节点`[]🇺🇲 美国节点`[]☑️ 手动切换
custom_proxy_group=☑️ 手动切换`select`.*
custom_proxy_group=♻️ 自动选择`url-test`.*`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=📹 油管视频`select`[]🚀 节点选择`[]♻️ 自动选择`[]☑️ 手动切换`[]DIRECT
custom_proxy_group=🎥 奈飞视频`select`[]🚀 节点选择`[]♻️ 自动选择`[]☑️ 手动切换`[]DIRECT`(NF|奈飞|解锁|Netflix|NETFLIX|Media|MITM)
custom_proxy_group=🌍 国外媒体`select`[]🚀 节点选择`[]♻️ 自动选择`[]🎯 全球直连`.*
custom_proxy_group=📲 电报信息`select`[]🚀 节点选择`[]🎯 全球直连`.*
custom_proxy_group=🤖 OpenAi`select`[]🚀 节点选择`[]♻️ 自动选择`[]🇺🇲 美国节点`[]🇭🇰 香港节点`[]🇯🇵 日本节点`[]🇸🇬 狮城节点`[]🇹🇼 台湾节点`[]🇰🇷 韩国节点`[]🇩🇪 德国节点`[]🇬🇧 英国节点`[]🇳🇱 荷兰节点`[]🇹🇷 土耳其节点`[]🇦🇺 澳大利亚节点`[]🇷🇺 俄罗斯节点`[]🇮🇳 印度节点`[]🇨🇦 加拿大节点`[]🇲🇾 马来西亚节点`[]🇧🇬 保加利亚节点`[]🇫🇷 法国节点`[]🇻🇳 越南节点`[]🇲🇳 蒙古节点`[]🇲🇴 澳门节点`[]🇸🇪 瑞典节点`[]🇮🇸 冰岛节点`[]🇮🇱 以色列节点`[]🇦🇪 阿联酋节点`[]🇵🇭 菲律宾节点`[]🇮🇪 爱尔兰节点`[]☑️ 手动切换`[]DIRECT
custom_proxy_group=Ⓜ️ 微软服务`select`[]🎯 全球直连`[]🚀 节点选择`.*
custom_proxy_group=🍎 苹果服务`select`[]🚀 节点选择`[]🎯 全球直连`.*
custom_proxy_group=📢 谷歌FCM`select`[]🚀 节点选择`[]🎯 全球直连`[]♻️ 自动选择`.*
custom_proxy_group=🎯 全球直连`select`[]DIRECT`[]🚀 节点选择`[]♻️ 自动选择
custom_proxy_group=🛑 全球拦截`select`[]REJECT`[]DIRECT
custom_proxy_group=🍃 应用净化`select`[]REJECT`[]DIRECT
custom_proxy_group=🐟 漏网之鱼`select`[]🚀 节点选择`[]🎯 全球直连`[]♻️ 自动选择`.*
custom_proxy_group=☁️ CloudFlareCDN`select`[]🐟 漏网之鱼`[]🚀 节点选择`[]🎯 全球直连`[]♻️ 自动选择`[]☑️ 手动切换
custom_proxy_group=🇭🇰 香港节点`load-balance`(港|HK|hk|Hong Kong|HongKong|hongkong|HKG)`http://www.gstatic.com/generate_204`300,,50
;custom_proxy_group=🇯🇵 日本节点`load-balance`(日本|川日|东京|大阪|泉日|埼玉|沪日|深日|[^-]日|JP|Japan)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇺🇲 美国节点`load-balance`(美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|US|United States|ATL|BUF|DFW|EWR|IAD|LAX|MCI|MIA|ORD|PHX|PDX|SEA|SJC)`http://www.gstatic.com/generate_204`300,,150
custom_proxy_group=🇭🇰 香港节点`url-test`(香港|Hong Kong|HongKong|hongkong|\bHK\b|\bHKG\b|🇭🇰)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇯🇵 日本节点`url-test`(日本|川日|东京|大阪|泉日|埼玉|沪日|深日|[^-]日|Japan|Tokyo|\bJP\b|\bJPN\b|\bNRT\b|\bKIX\b|🇯🇵)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇺🇲 美国节点`url-test`(美国|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|United States|\bUS\b|\bUSA\b|\bATL\b|\bBUF\b|\bDFW\b|\bEWR\b|\bIAD\b|\bLAX\b|\bMCI\b|\bMIA\b|\bORD\b|\bPHX\b|\bPDX\b|\bSEA\b|\bSJC\b|🇺🇸)`http://www.gstatic.com/generate_204`300,,150
custom_proxy_group=🇰🇷 韩国节点`url-test`(韩国|Korea|\bKR\b|\bKOR\b|Seoul|首尔|春川|韩|韓|\bICN\b|🇰🇷)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇮🇪 爱尔兰节点`url-test`(爱尔兰|Ireland|\bIE\b|\bIRL\b|Dublin|都柏林|🇮🇪)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇵🇭 菲律宾节点`url-test`(菲律宾|Philippines|\bPH\b|\bPHL\b|Manila|马尼拉|🇵🇭)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇦🇪 阿联酋节点`url-test`(阿联酋|\bUAE\b|\bAE\b|United Arab Emirates|🇦🇪)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇮🇱 以色列节点`url-test`(以色列|Israel|\bIL\b|\bISR\b|🇮🇱)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇮🇸 冰岛节点`url-test`(冰岛|Iceland|\bIS\b|\bISL\b|🇮🇸)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇸🇪 瑞典节点`url-test`(瑞典|Sweden|\bSE\b|\bSWE\b|Stockholm|斯德哥尔摩|🇸🇪)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇲🇴 澳门节点`url-test`(澳门|Macao|Macau|\bMO\b|\bMAC\b|🇲🇴)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇲🇳 蒙古节点`url-test`(蒙古|Mongolia|\bMN\b|\bMNG\b|🇲🇳)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇻🇳 越南节点`url-test`(越南|Vietnam|\bVN\b|\bVNM\b|Hanoi|河内|胡志明|🇻🇳)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇫🇷 法国节点`url-test`(法国|France|\bFR\b|\bFRA\b|Paris|巴黎|🇫🇷)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇧🇬 保加利亚节点`url-test`(保加利亚|Bulgaria|\bBG\b|\bBGR\b|🇧🇬)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇲🇾 马来西亚节点`url-test`(马来西亚|Malaysia|\bMY\b|\bMYS\b|Kuala|吉隆坡|🇲🇾)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇨🇦 加拿大节点`url-test`(加拿大|Canada|\bCA\b|\bCAN\b|Vancouver|Toronto|温哥华|多伦多|🇨🇦)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇮🇳 印度节点`url-test`(印度|India|\bIN\b|\bIND\b|Mumbai|孟买|🇮🇳)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇷🇺 俄罗斯节点`url-test`(俄罗斯|Russia|\bRU\b|\bRUS\b|Moscow|莫斯科|🇷🇺)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇦🇺 澳大利亚节点`url-test`(澳大利亚|澳洲|Australia|\bAU\b|\bAUS\b|Sydney|Melbourne|悉尼|墨尔本|🇦🇺)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇹🇷 土耳其节点`url-test`(土耳其|Turkey|\bTR\b|\bTUR\b|Istanbul|伊斯坦布尔|🇹🇷)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇳🇱 荷兰节点`url-test`(荷兰|Netherlands|\bNL\b|\bNLD\b|Amsterdam|阿姆斯坦丹|🇳🇱)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇬🇧 英国节点`url-test`(英国|United Kingdom|Great Britain|\bUK\b|\bGB\b|\bENG\b|\bGBR\b|London|伦敦|🇬🇧)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇩🇪 德国节点`url-test`(德国|Germany|\bDE\b|\bDEU\b|\bGER\b|Frankfurt|法兰克福|🇩🇪)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇹🇼 台湾节点`url-test`(台湾|Taiwan|\bTW\b|\bTWN\b|\bTPE\b|\bKHH\b|🇹🇼)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇸🇬 狮城节点`url-test`(新加坡|坡|狮城|Singapore|\bSG\b|\bSGP\b|\bSIN\b|🇸🇬)`http://www.gstatic.com/generate_204`300,,50



enable_rule_generator=true
overwrite_original_rules=true